### ISSUE TITLE
使用localhost访问正常，使用127.0.0.1访问提示跨域问题

### ISSUE THREAD

**Issue by SuperLong1210** [WonderLand33/BBS#12]
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access.

**Comment by 2206411193** [comment]
哦？

---原始邮件---
发件人:":D"<notifications@github.com>
发送时间:2020年1月13日 星期一 下午6:59
收件人:"champion97/BBS"<BBS@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:Re: [champion97/BBS] 使用localhost访问正常，使用127.0.0.1访问提示跨域问题 (#12)

Closed#12.

&mdash;
