### ISSUE TITLE
访问主页为空白

### ISSUE THREAD

**Issue by DoctorDeng** [WonderLand33/BBS#6]
在部署项目后，访问 http://localhost:8080/ 为空白，

**Comment by x-pengg** [comment]
可能是部署出现的问题，检查下控制台 jetty 是否成功启动，jetty默认端口是8080，在`pom.xml`里面有配置；再检查下`env-config.properties`里面的domain端口是否与其一致。

btw:这个项目是早些年学习时写下的，BUG很多也一致没维护，不推荐使用在生成环境 ：）
