### ISSUE TITLE
本地环境运行访问任何页面404

### ISSUE THREAD

**Issue by iwangjie** [WonderLand33/BBS#8]
Mysql5.7  jetty运行，访问登录页面404

**Comment by x-pengg** [comment]
抱歉，jetty目前没有测试过，tomcat访问的正确地址是：`http://localhost:8080`

如果尝试仍然不行，那么可能是SpringMVC在jetty与tomcat之间存在差异。你尝试修改一下在SpringMVC返回一个view的时候，加上前置路径分隔符

 比如：
```Java
    @RequestMapping("")
    public String index() {
        return "/home/index"; // 加上前置路径分隔符
    }
```
